import keyMirror from 'keymirror';

const action = keyMirror({
  // ajax calls
  BEGIN_AJAX_CALL: null,
  AJAX_CALL_ERROR: null,

  // Error calls
  ERROR_SET_SUCCESS: null,
  ERROR_SET_FAILED: null,

  // trigger calls
  SET_TRIGGER_SUCCESS: null,
  SET_TRIGGER_FAILED: null,
  GET_TRIGGER_SUCCESS: null,
  GET_TRIGGER_FAILED: null,

  // date time
  SET_DATETIME_SUCCESS: null,
  SET_DATETIME_FAILED: null,
  GET_DATETIME_SUCCESS: null,
  GET_DATETIME_FAILED: null,

  // start date
  SET_START_DATE_SUCCESS: null,
  SET_START_DATE_FAILED: null,
  GET_START_DATE_SUCCESS: null,
  GET_START_DATE_FAILED: null,

  // course actions
  LOAD_COURSES_SUCCESS: null,
  CREATE_COURSE_SUCCESS: null,
  UPDATE_COURSE_SUCCESS: null,

  // author actions
  LOAD_AUTHORS_SUCCESS: null,

  // race actions
  LOAD_RACES_SUCCESS: null,
  LOAD_RACES_FAILED: null,
  LOAD_RACE_SUCCESS: null,
  LOAD_RACE_FAILED: null,
  CREATE_RACE_SUCCESS: null,
  CREATE_RACE_FAILED: null,
  UPDATE_RACE_SUCCESS: null,
  UPDATE_RACE_FAILED: null,
  DELETE_RACE_SUCCESS: null,
  DELETE_RACE_FAILED: null,

  // phone actions
  LOAD_PHONES_SUCCESS: null,
  LOAD_PHONES_FAILED: null,
  CREATE_PHONE_SUCCESS: null,
  CREATE_PHONE_FAILED: null,
  UPDATE_PHONE_SUCCESS: null,
  UPDATE_PHONE_FAILED: null,

  // student actions
  LOAD_STUDENTS_SUCCESS: null,
  LOAD_STUDENTS_FAILED: null,
  LOAD_STUDENT_SUCCESS: null,
  LOAD_STUDENT_FAILED: null,
  CREATE_STUDENT_SUCCESS: null,
  UPDATE_STUDENT_SUCCESS: null,
  CREATE_STUDENT_FAILED: null,
  UPDATE_STUDENT_FAILED: null,

  // person complete actions
  LOAD_PERSONCOMPLETES_SUCCESS: null,
  LOAD_PERSONCOMPLETES_FAILED: null,
  LOAD_PERSONCOMPLETE_SUCCESS: null,
  LOAD_PERSONCOMPLETE_FAILED: null,

  // person type actions
  LOAD_PERSON_TYPES_SUCCESS: null,
  LOAD_PERSON_TYPES_FAILED: null,
  LOAD_PERSON_TYPE_SUCCESS: null,
  LOAD_PERSON_TYPE_FAILED: null,
  FORM_CHANGE_PERSON_SUCCESS: null,
  FORM_CHANGE_PERSON_FAILED: null,
  CREATE_PERSON_TYPE_SUCCESS: null,
  UPDATE_PERSON_TYPE_SUCCESS: null,
  CREATE_PERSON_TYPE_FAILED: null,
  UPDATE_PERSON_TYPE_FAILED: null,
  DELETE_PERSON_TYPE_SUCCESS: null,
  DELETE_PERSON_TYPE_FAILED: null,

  // person actions
  LOAD_PERSONS_SUCCESS: null,
  LOAD_PERSONS_FAILED: null,
  LOAD_PERSON_SUCCESS: null,
  LOAD_PERSON_FAILED: null,
  CREATE_PERSON_SUCCESS: null,
  UPDATE_PERSON_SUCCESS: null,
  CREATE_PERSON_FAILED: null,
  UPDATE_PERSON_FAILED: null,
  DELETE_PERSON_SUCCESS: null,
  DELETE_PERSON_FAILED: null,

  // account actions
  LOAD_ACCOUNTS_SUCCESS: null,
  LOAD_ACCOUNTS_FAILED: null,
  LOAD_ACCOUNT_SUCCESS: null,
  LOAD_ACCOUNT_FAILED: null,
  CREATE_ACCOUNT_SUCCESS: null,
  UPDATE_ACCOUNT_SUCCESS: null,
  CREATE_ACCOUNT_FAILED: null,
  UPDATE_ACCOUNT_FAILED: null,
  DELETE_ACCOUNT_SUCCESS: null,
  DELETE_ACCOUNT_FAILED: null,

  // invoice actions
  LOAD_INVOICES_SUCCESS: null,
  LOAD_INVOICES_FAILED: null,
  LOAD_INVOICE_SUCCESS: null,
  LOAD_INVOICE_FAILED: null,
  CREATE_INVOICE_SUCCESS: null,
  UPDATE_INVOICE_SUCCESS: null,
  CREATE_INVOICE_FAILED: null,
  UPDATE_INVOICE_FAILED: null,
  DELETE_INVOICE_SUCCESS: null,
  DELETE_INVOICE_FAILED: null,

  // total invoice actions
  LOAD_TOTALINVOICES_SUCCESS: null,
  LOAD_TOTALINVOICES_FAILED: null,
  LOAD_TOTALINVOICE_SUCCESS: null,
  LOAD_TOTALINVOICE_FAILED: null,
  CREATE_TOTALINVOICE_SUCCESS: null,
  UPDATE_TOTALINVOICE_SUCCESS: null,
  CREATE_TOTALINVOICE_FAILED: null,
  UPDATE_TOTALINVOICE_FAILED: null,
  DELETE_TOTALINVOICE_SUCCESS: null,
  DELETE_TOTALINVOICE_FAILED: null,

  // state actions
  GET_STATES_SUCCESS: null,
  GET_STATES_FAILED: null,

  // address actions
  GET_ALL_ADDRESSES_SUCCESS: null,
  GET_ALL_ADDRESSES_FAILED: null,
  GET_ADDRESS_SUCCESS: null,
  GET_ADDRESS_FAILED: null,
  GET_PERSON_ADDRESSES_SUCCESS: null,
  GET_PERSON_ADDRESSES_FAILED: null,
  CREATE_ADDRESS_SUCCESS: null,
  CREATE_ADDRESS_FAILED: null,
  UPDATE_ADDRESS_SUCCESS: null,
  UPDATE_ADDRESS_FAILED: null,
  DELETE_ADDRESS_SUCCESS: null,
  DELETE_ADDRESS_FAILED: null,

  // address actions
  LOAD_ADDRESS_TYPES_SUCCESS: null,
  LOAD_ADDRESS_TYPES_FAILED: null,
  CREATE_ADDRESS_TYPE_SUCCESS: null,
  CREATE_ADDRESS_TYPE_FAILED: null,
  UPDATE_ADDRESS_TYPE_SUCCESS: null,
  UPDATE_ADDRESS_TYPE_FAILED: null,
  DELETE_ADDRESS_TYPE_SUCCESS: null,
  DELETE_ADDRESS_TYPE_FAILED: null,

  // student status actions
  LOAD_STUDENT_STATUSES_SUCCESS: null,
  LOAD_STUDENT_STATUSES_FAILED: null,
  CREATE_STUDENT_STATUS_SUCCESS: null,
  UPDATE_STUDENT_STATUS_SUCCESS: null,
  CREATE_STUDENT_STATUS_FAILED: null,
  UPDATE_STUDENT_STATUS_FAILED: null,
  DELETE_STUDENT_STATUS_SUCCESS: null,
  DELETE_STUDENT_STATUS_FAILED: null,

  // state actions
  LOAD_ACCOUNTADDRESSES_SUCCESS: null,
  LOAD_ACCOUNTADDRESSES_FAILED: null
});

export default action;
